### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sky5454** [sky5454/myORM-jdbc#4]
1. Code
 - [x] print SQL   by `pstmt.toString()` 
 - [x] close pstmt
 - [ ] Preload Method's Annotation
 - [ ] Optimize tabulation symbols use
 - [ ] Auto Commit and Transaction Commit
 - [ ] Github Actions
 - [ ] Fix `//TODO` 
 - [ ] the Pool of table DBsource
 - [ ] the Pool of pstmt, then exec
 - [ ] Log System `refer: log4jdbc 是一个在JDBC层的日志框架`
 - [ ] Multi Thread
 - [ ] Gradle support

2. Docs
 - [ ] **docs :** use it as you are using pstmt
 - [ ] refer to JDBC ResultSet to Java Class. such as BigInt->Long.
